import turtle as birdseyepyramid

birdseyepyramid.dot()
birdseyepyramid.penup()
birdseyepyramid.forward(75)
birdseyepyramid.pendown()
birdseyepyramid.setheading(270)
birdseyepyramid.forward(75)
birdseyepyramid.dot()
birdseyepyramid.setheading(180)

birdseyepyramid.forward(15)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(37.5)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(37.5)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(15)

birdseyepyramid.dot()
birdseyepyramid.setheading(90)
birdseyepyramid.forward(150)
birdseyepyramid.dot()
birdseyepyramid.setheading(0)

birdseyepyramid.forward(15)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(37.5)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(37.5)
birdseyepyramid.penup()
birdseyepyramid.forward(15)
birdseyepyramid.pendown()
birdseyepyramid.forward(15)

birdseyepyramid.dot()
birdseyepyramid.setheading(270)
birdseyepyramid.forward(150)
birdseyepyramid.setheading(135)
birdseyepyramid.forward(212)
birdseyepyramid.setheading(270)
birdseyepyramid.forward(150)
birdseyepyramid.setheading(45)
birdseyepyramid.forward(212)

birdseyepyramid.hideturtle()